pipeline{
    agents{
        label "any"
    }
    Enviornment{

    }
    stages{
        stage (scm checkout){
            dir(){
                steps{

                }
            }
        }
        stage(){
            dir(){
                withCredentials(
                    [usernmaePassword(
                        credentialId:
                        usernameVariable:
                        passwordVariable:
                        )]
                )
            }
        }
    }
}