pipeline{
    agents{
        label "any"
    }
    Enviornment{
        DOCKERUSER = "shriram2105"
        IMAGENAME  = "python-web-app"
        IMAGETAG   = "1.0.1"
    }
    stages{
        stage (scm checkout){
            dir(){
                steps{

                }
            }
        }
        stage(){
            dir(){
                withCredentials(
                    [usernmaePassword(
                        credentialId:
                        usernameVariable:
                        passwordVariable:
                        )]
                )
            }
        }
    }
}